# Generated by Django 3.1 on 2020-12-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('matches', '0002_auto_20201207_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ManyToManyField(blank=True, null=True, related_name='won_matches', to='teams.Team'),
        ),
    ]
