# Generated by Django 3.1 on 2020-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0001_initial'),
        ('matches', '0004_auto_20201207_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='secondary_casters',
            field=models.ManyToManyField(blank=True, related_name='cocasted_matches', to='casters.Caster'),
        ),
    ]
