# Generated by Django 3.1 on 2020-12-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('matches', '0005_auto_20201213_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_berries', models.PositiveSmallIntegerField(default=0)),
                ('away_berries', models.PositiveSmallIntegerField(default=0)),
                ('home_snail', models.PositiveSmallIntegerField(default=0)),
                ('away_snail', models.PositiveSmallIntegerField(default=0)),
                ('home_queen_deaths', models.PositiveSmallIntegerField(default=0)),
                ('away_queen_deaths', models.PositiveSmallIntegerField(default=0)),
                ('win_condition', models.CharField(blank=True, choices=[('E', 'Economic'), ('M', 'Military'), ('S', 'Snail')], max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_sets_won',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_sets_won',
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='matches.game')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='teams.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='matches.match')),
                ('sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='matches.set')),
            ],
        ),
    ]
