# Generated by Django 3.1 on 2020-12-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20201214_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matches.result'),
        ),
    ]
