# Generated by Django 3.1 on 2020-12-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_auto_20201214_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='sets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='matches.set'),
        ),
    ]
