# Generated by Django 3.1 on 2020-12-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('matches', '0009_auto_20201214_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='teams.team'),
        ),
        migrations.AddField(
            model_name='result',
            name='loser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lost_match_results', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='won_match_results', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='sets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='matches.set'),
        ),
        migrations.AlterField(
            model_name='set',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_sets', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='set',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_sets', to='teams.team'),
        ),
    ]
