# Generated by Django 3.1 on 2020-12-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20201214_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_berries',
            field=models.PositiveSmallIntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_queen_deaths',
            field=models.PositiveSmallIntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_snail',
            field=models.PositiveSmallIntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_berries',
            field=models.PositiveSmallIntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_queen_deaths',
            field=models.PositiveSmallIntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_snail',
            field=models.PositiveSmallIntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='matches.result'),
        ),
    ]
