# Generated by Django 3.1 on 2020-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_auto_20201214_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='win_condition',
            field=models.CharField(blank=True, choices=[('PD', 'The Pod'), ('TF', 'The Tally Fields'), ('NF', 'The Nesting Flats'), ('SJ', 'Split Juniper'), ('BQ', "Black Queen's Keep"), ('HT', 'Helix Temple'), ('SP', 'The Spire')], max_length=2, null=True),
        ),
    ]
