# Generated by Django 3.1 on 2020-12-15 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20201215_2231'),
        ('matches', '0015_auto_20201214_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.round'),
            preserve_default=False,
        ),
    ]
