# Generated by Django 3.1 on 2020-12-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0007_auto_20201216_1020'),
        ('matches', '0018_auto_20201215_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='secondary_casters',
            field=models.ManyToManyField(blank=True, null=True, related_name='cocasted_matches', to='casters.Caster'),
        ),
    ]
