# Generated by Django 3.1 on 2020-12-27 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20201220_0210'),
        ('matches', '0020_auto_20201216_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.round'),
        ),
    ]
