# Generated by Django 3.1 on 2021-03-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_auto_20201231_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_berries',
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_queen_deaths',
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_snail',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_berries',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_queen_deaths',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_snail',
        ),
    ]
