# Generated by Django 3.1 on 2021-03-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_auto_20210321_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('body', models.JSONField()),
                ('set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='matches.set')),
            ],
        ),
    ]
