# Generated by Django 3.1 on 2021-03-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_setlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlog',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
