# Generated by Django 3.1 on 2021-03-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20210301_0932'),
        ('players', '0014_auto_20210318_1829'),
        ('matches', '0025_auto_20210322_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_results', to='players.player'),
        ),
        migrations.AddField(
            model_name='result',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='source',
            field=models.CharField(blank=True, choices=[('UL', 'Match Uploader'), ('SH', 'Google Sheets'), ('AM', 'Buzz Admin')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='TeamMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('gold', 'Gold')], max_length=4)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_mappings', to='matches.result')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_mapping', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Team Mappings',
            },
        ),
        migrations.CreateModel(
            name='PlayerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_mapping', to='players.player')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_mappings', to='matches.result')),
            ],
            options={
                'verbose_name_plural': 'Player Mappings',
            },
        ),
    ]
