# Generated by Django 3.1 on 2021-03-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0026_auto_20210330_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermapping',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='teammapping',
            name='color',
            field=models.CharField(choices=[(2, 'Blue'), (1, 'Gold')], max_length=1),
        ),
    ]
