# Generated by Django 3.1 on 2021-04-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0027_auto_20210330_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammapping',
            name='color',
            field=models.IntegerField(choices=[(2, 'Blue'), (1, 'Gold')], max_length=1),
        ),
    ]
