# Generated by Django 3.1 on 2021-05-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0028_auto_20210404_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
