# Generated by Django 3.1 on 2021-06-07 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0028_auto_20210429_2031'),
        ('matches', '0030_auto_20210523_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_matches', to='leagues.group'),
        ),
    ]
