# Generated by Django 3.1 on 2020-12-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to='players.player')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.circuit')),
                ('members', models.ManyToManyField(blank=True, related_name='member_of', to='players.Player')),
            ],
        ),
    ]
