# Generated by Django 3.1 on 2021-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20201229_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
