# Generated by Django 3.1 on 2021-03-01 09:24
from django.db import migrations
from teams.models import _generate_invite_code

def set_team_invite_codes(apps, schema_editor):
    """
    Add invite code to all teams in database.
    """
    Team = apps.get_model('teams', 'Team')
    for team in Team.objects.all():
        team.invite_code = _generate_invite_code()
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_invite_code'),
    ]

    operations = [migrations.RunPython(set_team_invite_codes)]
