# Generated by Django 3.1 on 2021-03-01 09:29

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210301_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(default=teams.models._generate_invite_code, max_length=8, unique=True),
        ),
    ]
