# Generated by Django 3.1 on 2021-05-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_team_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='emoji',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
