# Generated by Django 3.1 on 2021-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20210505_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='emoji',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
