# Generated by Django 3.1 on 2020-12-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casters_csv_url', models.URLField()),
            ],
        ),
    ]
