# Generated by Django 3.1 on 2020-12-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0002_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
        migrations.AddField(
            model_name='settings',
            name='ignore_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
