# Generated by Django 3.1 on 2020-12-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0003_auto_20201215_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('caster_name', models.CharField(max_length=255)),
            ],
        ),
    ]
