# Generated by Django 3.1 on 2020-12-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0005_caster_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='namemapping',
            name='does_solo_casts',
            field=models.BooleanField(default=True),
        ),
    ]
