# Generated by Django 3.1 on 2020-12-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0006_namemapping_does_solo_casts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namemapping',
            name='does_solo_casts',
        ),
        migrations.AddField(
            model_name='caster',
            name='does_solo_casts',
            field=models.BooleanField(default=True),
        ),
    ]
