# Generated by Django 3.1 on 2020-12-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20201213_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
