# Generated by Django 3.1 on 2020-12-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_season_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='team_csv_url',
            new_name='teams_csv_url',
        ),
    ]
