# Generated by Django 3.1 on 2020-12-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20201215_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='is_bracket',
            field=models.BooleanField(default=False),
        ),
    ]
