# Generated by Django 3.1 on 2020-12-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20201215_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='is_bracket',
            new_name='is_tournament',
        ),
    ]
