# Generated by Django 3.1 on 2020-12-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20201215_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='is_tournament',
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.circuit')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.bracket'),
        ),
    ]
