# Generated by Django 3.1 on 2020-12-16 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20201215_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='circuit',
        ),
        migrations.AddField(
            model_name='round',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
            preserve_default=False,
        ),
    ]
