# Generated by Django 3.1 on 2020-12-16 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_auto_20201216_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='league',
        ),
        migrations.AddField(
            model_name='round',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.season'),
            preserve_default=False,
        ),
    ]
