# Generated by Django 3.1 on 2020-12-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_auto_20201216_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['bracket', 'round_number', '-name']},
        ),
    ]
