# Generated by Django 3.1 on 2020-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_auto_20201216_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='awards_csv_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
