# Generated by Django 3.1 on 2020-12-20 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_season_awards_csv_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='leagues.season'),
        ),
    ]
