# Generated by Django 3.1 on 2020-12-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20201220_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='region',
            field=models.CharField(choices=[('W', 'West'), ('E', 'East'), ('A', 'All'), ('Wa', 'All'), ('Wb', 'All')], max_length=2),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='tier',
            field=models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3'), ('4', 'Tier 4'), ('0', 'No Tier')], max_length=2),
        ),
    ]
