# Generated by Django 3.1 on 2020-12-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_auto_20201229_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='region',
            field=models.CharField(choices=[('W', 'West'), ('E', 'East'), ('A', 'All'), ('Wa', 'West A'), ('Wb', 'West B')], max_length=2),
        ),
    ]
