# Generated by Django 3.1 on 2021-01-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0017_auto_20201229_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['bracket', 'round_number_new', '-name']},
        ),
        migrations.RemoveField(
            model_name='round',
            name='round_number',
        ),
        migrations.AddField(
            model_name='round',
            name='round_number_new',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=4, null=True),
        ),
    ]
