# Generated by Django 3.1 on 2021-02-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_auto_20210110_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
