# Generated by Django 3.1 on 2021-03-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0020_auto_20210228_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='rosters_open',
            field=models.BooleanField(default=False),
        ),
    ]
