# Generated by Django 3.1 on 2021-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0021_season_rosters_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='max_team_members',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
