# Generated by Django 3.1 on 2021-04-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_auto_20210311_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_number', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=4, null=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='leagues.season')),
            ],
        ),
    ]
