# Generated by Django 3.1 on 2021-04-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0024_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_number',
            new_name='number',
        ),
    ]
