# Generated by Django 3.1 on 2021-04-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0027_season_current_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='current_round',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_round_season', to='leagues.round'),
        ),
    ]
