# Generated by Django 3.1 on 2020-12-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
                ('service', models.CharField(choices=[('TW', 'Twitch'), ('YT', 'Youtube')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='StreamerBlacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
