# Generated by Django 3.1 on 2020-12-23 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='max_viewer_count',
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_id',
            field=models.PositiveSmallIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='thumbnail_url',
            field=models.CharField(default='http://www.google.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
