# Generated by Django 3.1 on 2020-12-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20201223_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(max_length=255),
        ),
    ]
