# Generated by Django 3.1 on 2020-12-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_auto_20201223_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='max_viewer_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
