# Generated by Django 3.1 on 2020-12-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_auto_20201223_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
