# Generated by Django 3.1 on 2020-12-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20201223_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='max_viewer_count',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
