# Generated by Django 3.1 on 2020-12-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20201227_1928'),
        ('streams', '0007_auto_20201227_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams', to='players.player'),
        ),
    ]
