# Generated by Django 3.1 on 2020-12-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='twitch_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
