# Generated by Django 3.1 on 2020-12-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20201214_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_phonetic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pronouns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
