# Generated by Django 3.1 on 2020-12-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20201216_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='discord_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
