# Generated by Django 3.1 on 2021-01-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20201227_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_csv_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
