# Generated by Django 3.1 on 2021-01-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_playersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playersettings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='alias',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
