# Generated by Django 3.1 on 2021-01-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20210109_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alias',
            old_name='primary',
            new_name='is_primary',
        ),
    ]
