# Generated by Django 3.1 on 2021-03-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20210227_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGLPlayerLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_uid', models.CharField(max_length=255)),
                ('discord_username', models.CharField(max_length=255)),
                ('igl_player_name', models.CharField(max_length=255)),
            ],
        ),
    ]
