# Generated by Django 3.1 on 2020-12-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardcategory',
            options={'verbose_name_plural': 'Award Categories'},
        ),
        migrations.AlterModelOptions(
            name='statcategory',
            options={'verbose_name_plural': 'Stat Categories'},
        ),
        migrations.AlterField(
            model_name='stat',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
