# Generated by Django 3.1 on 2020-12-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20201213_2206'),
        ('awards', '0002_auto_20201215_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='circuit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='leagues.circuit'),
            preserve_default=False,
        ),
    ]
