# Generated by Django 3.1 on 2020-12-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_award_circuit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='week_number',
            new_name='round_number',
        ),
    ]
