# Generated by Django 3.1 on 2020-12-20 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20201220_0210'),
        ('awards', '0004_auto_20201215_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='round_number',
        ),
        migrations.AddField(
            model_name='award',
            name='round',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='leagues.round'),
            preserve_default=False,
        ),
    ]
