# Generated by Django 3.1 on 2020-12-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20201220_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='stats',
            field=models.ManyToManyField(related_name='award', to='awards.Stat'),
        ),
    ]
