# Generated by Django 3.1 on 2020-12-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
                ('total', models.PositiveSmallIntegerField()),
                ('platform', models.CharField(choices=[('ST', 'Steam'), ('SW', 'Nintendo Switch'), ('XB', 'Xbox')], default='ST', max_length=2)),
                ('operating_system', models.CharField(blank=True, choices=[('WIN', 'Windows'), ('MAC', 'Mac OS'), ('LIN', 'Linux')], max_length=3, null=True)),
                ('ranked_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quickplay_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('custom_total', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('buildid', models.PositiveSmallIntegerField()),
                ('released_on', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('message', models.TextField()),
                ('platform', models.CharField(choices=[('ST', 'Steam'), ('SW', 'Nintendo Switch'), ('XB', 'Xbox')], default='ST', max_length=2)),
            ],
        ),
    ]
