# Generated by Django 3.1 on 2020-12-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playing',
            options={'verbose_name_plural': 'Playing'},
        ),
        migrations.AlterField(
            model_name='release',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
