# Generated by Django 3.1 on 2020-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegame', '0002_auto_20201223_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
