name: Buzz API Django App

on:
  push:
    branches: [ mvp ]
  pull_request:
    branches: [ mvp ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: buzz.settings.github
      GET_SECRETS_FROM_ENV: true
      SECRET_KEY: dontusethisanywhereelse3jFF8gbVcEcdontusethisanywCrbDHKEZVM
      TWITCH_CLIENT_ID: abc123
      TWITCH_CLIENT_SECRET: abc123

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.github.txt; fi
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: pytest
  
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.GITDEPLOY_SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.GITDEPLOY_SSH_KNOWN_HOSTS}}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
    
    - name: Deploy to Server
      run: ssh -i $SSH_KEY_PATH ${{secrets.GITDEPLOY_SSH_USER_HOSTNAME}} python3 ${{secrets.STAGING_REMOTE_PROJECT_PATH}}/deploy.py
