name: Buzz API Django App

on:
  push:
    branches: [ mvp ]
  pull_request:
    branches: [ mvp ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: buzz.settings.github

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.github.txt; fi
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: pytest