name: Staging Run Tests & Deploy

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: buzz.settings.github
      GET_SECRETS_FROM_ENV: true
      SECRET_KEY: ${{secrets.CI_DJANGO_SECRET_KEY}}
      TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
      TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.10

    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.github.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.github.txt; fi
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: pytest
  
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.GITDEPLOY_SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.GITDEPLOY_SSH_KNOWN_HOSTS}}

    - name: Deploy to Server
      run: |
        ssh -i $SSH_KEY_PATH -t ${{secrets.GITDEPLOY_SSH_USER_HOSTNAME}} "cd ${{secrets.STAGING_REMOTE_PROJECT_PATH}}/buzz;/usr/bin/git pull"
        ssh -i $SSH_KEY_PATH -t ${{secrets.GITDEPLOY_SSH_USER_HOSTNAME}} "${{secrets.STAGING_REMOTE_PROJECT_PATH}}/env/bin/pip install -r ${{secrets.STAGING_REMOTE_PROJECT_PATH}}/buzz/requirements.txt"
        ssh -i $SSH_KEY_PATH -t ${{secrets.GITDEPLOY_SSH_USER_HOSTNAME}} "${{secrets.STAGING_REMOTE_PROJECT_PATH}}/env/bin/python ${{secrets.STAGING_REMOTE_PROJECT_PATH}}/buzz/manage.py migrate --settings=buzz.settings.staging"
        ssh -i $SSH_KEY_PATH -t ${{secrets.GITDEPLOY_SSH_USER_HOSTNAME}} "${{secrets.STAGING_REMOTE_PROJECT_PATH}}/env/bin/python ${{secrets.STAGING_REMOTE_PROJECT_PATH}}/buzz/manage.py collectstatic --no-input --settings=buzz.settings.staging"
        ssh -i $SSH_KEY_PATH -tt ${{secrets.GITDEPLOY_SSH_USER_HOSTNAME}} "touch ${{secrets.STAGING_REMOTE_PROJECT_PATH}}/buzz/buzz/wsgi.py"
      env:
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key

    - name: Post results to \#tech-logs
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_DEPLOY_WEBHOOK }}
        DISCORD_EMBEDS: '[{"title": "api-staging.beegame.gg", "description": "All tests passed, migrations ran, deployed! <:dancebluestripes:811497254329253909> "}]'
      uses: Ilshidur/action-discord@8135f7f8f567c49fa55ada203fcf37b4888a4001
      with:
        args: ''