name: Staging Run Tests

on:
  push:
    branches: [ mvpdev ]
  pull_request:
    branches: [ mvpdev ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: buzz.settings.github
      GET_SECRETS_FROM_ENV: true
      SECRET_KEY: ${{secrets.CI_DJANGO_SECRET_KEY}}
      TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
      TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.10

    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.github.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.github.txt; fi
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: pytest
  